language: python

python:
  - "3.7"

branches:
  only:
    - master

install:
  - pip install pipenv
  - pipenv install
  - cd frontend/
  - npm install jest
  - cd ../

script:
  - make test_backend
  - make test_frontend