language: python

python:
  - "3.7"

services:
  - docker

branches:
  only:
    - master

install:
  - pip install pipenv
  - pipenv install
  - cd frontend/
  - npm install jest
  - cd ../

script:
  - make test_backend
  - make test_frontend
  - npm uninstall jest
  - make up
  - make status