language: python

python:
  - "3.7"

env: DJANGO_SETTINGS_MODULE="leia_backend.settings.testing"

services:
  - docker
  - postgresql

branches:
  only:
    - master

install:
  - pip install pipenv
  - pipenv install
  - cd frontend/
  - npm install jest@24.9.0
  - cd ../

script:
  - make test_backend
  - make test_frontend
  # - make build
  # - make status