version: "3.2"
services:
  db:
    image: postgres:11.1-alpine
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=leia_backend.settings.development
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
