# Generated by Django 3.0.4 on 2020-03-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia', '0003_taxon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='extinction_date',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='former_range',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='order',
        ),
        migrations.AddField(
            model_name='taxon',
            name='endemic_of',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taxon',
            name='taxon_superior',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taxon',
            name='taxonomic_rank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='binomial_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='common_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='page_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='picture',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
