# Generated by Django 3.0.5 on 2020-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='cites_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
