# Generated by Django 3.0.5 on 2020-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0002_taxon_cites_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='binomial_name',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='cites_id',
            new_name='genus',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='common_name',
            new_name='kingdom',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='taxon_superior',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='taxon',
            old_name='taxonomic_rank',
            new_name='order',
        ),
        migrations.AddField(
            model_name='taxon',
            name='phylum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taxon',
            name='scientific_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taxon',
            name='species',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taxon',
            name='taxon_class',
            field=models.CharField(default='', max_length=100),
        ),
    ]
