# Generated by Django 3.0.5 on 2020-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0003_auto_20200419_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='distribution',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='taxon',
            name='gbif_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
