# Generated by Django 3.0.5 on 2020-04-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0004_auto_20200419_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='gbif_key',
            field=models.IntegerField(),
        ),
    ]
