# Generated by Django 3.0.5 on 2020-04-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0005_auto_20200419_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='page_id',
            field=models.IntegerField(),
        ),
    ]
