# Generated by Django 3.0.5 on 2020-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0006_auto_20200419_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='page_id',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='picture',
            field=models.URLField(),
        ),
    ]
