# Generated by Django 3.0.5 on 2020-04-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0008_auto_20200419_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='gbif_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
