# Generated by Django 3.0.5 on 2020-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0009_auto_20200419_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='picture_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='taxon',
            name='picture_src',
            field=models.CharField(default='', max_length=200),
        ),
    ]
