# Generated by Django 3.0.5 on 2020-04-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0010_auto_20200419_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='endemic_of',
            new_name='vernacular_name',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='picture_description',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='picture_src',
        ),
    ]
