# Generated by Django 3.0.5 on 2020-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_api', '0011_auto_20200426_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='picture',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
