# Generated by Django 3.0.3 on 2020-03-22 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('common_name', models.CharField(max_length=100)),
                ('binomial_name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('extinction_date', models.CharField(max_length=100)),
                ('former_range', models.CharField(max_length=100)),
                ('picture', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Leia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
