# Generated by Django 3.0.3 on 2020-03-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia', '0002_leia_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_name', models.CharField(max_length=100)),
                ('taxon_endemic_to', models.CharField(max_length=200)),
                ('taxon_extinction_date', models.CharField(max_length=100)),
                ('taxon_common_category', models.CharField(max_length=100)),
                ('taxon_image', models.URLField()),
            ],
        ),
    ]
