# Generated by Django 3.0.3 on 2020-03-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia', '0003_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='taxon_image',
            field=models.URLField(default=None),
        ),
    ]
